# @package _global_

# Define key values here that are used multiple times in the config files.
dataset_root: <path to your shapenet dataset root>
dataset_kind: noether.data.datasets.cfd.ShapeNetCarDataset

config_schema_kind: tutorial.schemas.development_schema.DevelopmentConfigSchema
excluded_properties: 
  - surface_friction
  - volume_pressure
  - volume_vorticity

defaults:
  - data_specs: development
  - dataset_normalizers: shapenet_dataset_normalizers
  - dataset_statistics: shapenet_car_stats
  - model: development_model # models are undefined and will be defined per experiment 
  - trainer: development_trainer
  - datasets: development_dataset
  - callbacks: development_callback
  - pipeline: development_pipeline
  - optimizer: adamw

output_path: '' #TODO: remove this 

# fix dependencies between trainer and model by defining them both here. This is a temporary solution until we have a more robust way of handling dependencies between config components.