# @package _global_

defaults:
  - data_specs: caeml
  - dataset_normalizers: caeml_dataset_normalizers
  - dataset_statistics: drivaernet++_stats
  - model: "???"
  - trainer: caeml_trainer
  - datasets: caeml_dataset
  - tracker: "??"
  - callbacks: training_callbacks_caeml
  - pipeline: caeml_pipeline
  - /pipeline@inference_pipeline: caeml_pipeline
  - optimizer: __OPTIMIZER__
  - _self_

dataset_root: __DATASET_PATH__
dataset_kind: noether.data.datasets.cfd.DrivAerNetDataset
config_schema_kind: __PROJECT__.schemas.config_schema.ConfigSchema
excluded_properties:
  - volume_sdf
  - volume_normals
  - surface_normals
stage_name: train
store_code_in_output: false
output_path: ./outputs
